cleEntry = {None, PURPLE , ORANGE , EWMA_SHAREABLE , XDLINKAGE_GET_EWMA }; 
cdf = {None_cdf_0, None_cdf_1 , None_cdf_2 , EWMA_SHAREABLE_cdf_0 , XDLINKAGE_GET_EWMA_cdf_0 }; 
remotelevel = {None_remotelevel_0, None_remotelevel_1 , None_remotelevel_2 , EWMA_SHAREABLE_remotelevel_0 , XDLINKAGE_GET_EWMA_remotelevel_0 }; 
haslevel = [none, purple , orange , orange , orange ]; 
hasremotelevel = [none, none , none , purple , purple ]; 
hasdirection = [noDir, noDir , noDir , egress , bidirectional ]; 
hasoperation = [noOp, noOp , noOp , allow , allow ]; 
hasCDF = [|None_cdf_0|None_cdf_1|None_cdf_2|EWMA_SHAREABLE_cdf_0|XDLINKAGE_GET_EWMA_cdf_0|]; 
