#!/bin/bash

die () {
    echo >&2 "$@"
    exit 1
}

if [[ ("$#" -ne 1) && ("$#" -ne 2) ]]
then
    die $'usage: ./test-p3 [feasible|infeasible] prog_name\n       ./test-p3  all'
fi
if [[ ("$1" != "all") && ("$1" != "feasible") && ("$1" != "infeasible") ]]
then
    die "error: first arugment must be one of: all, feasible, infeasible"
fi
if [[ (("$1" == "feasible") || ("$1" == "infeasible")) && ("$#" != 2) ]]
then
    die "error: first argument is [feasible|infeasible] but no prog_name given"
fi

run () {
    ERR=$'\n    conflict analysis errored (see above)'
       mkdir tmp-ca \
    && python3 -m conflict_analyzer --temp-dir tmp-ca --pdg-lib ../../pdg2/build/libpdg.so --dump-ptg ../../pdg2/svf/Release-build/bin/dump-ptg tests/$1/$2/$2.c 2>&1 >ca-output.txt \
    && touch tests/$1/$2/artifacts/xyzxyz \
    && rm tests/$1/$2/artifacts/* \
    && mv tmp-ca/* tests/$1/$2/artifacts \
    && rm -rf tmp-ca
    
    if [[ $? -ne 0 ]]
    then
        (rm -rf tmp-ca 2> /dev/null && echo $"FAILURE $1/$2 $ERR")
    else
        minizinc tests/$1/$2/artifacts/instance.mzn | tail -n 1 | grep -q "UNSATISFIABLE"
        STATUS=$?
        if [[ ($STATUS == 0 && "$1" == "feasible") ]]
        then
            ERR=$'\n    instance.mzn is unsatisfiable'
            EDGE=$'\n    TODO: edge diff'
            echo $"FAILURE $1/$2 $ERR $EDGE"
        elif [[ ($STATUS != 0 && "$1" == "infeasible") ]]
        then
            ERR=$'\n    instance.mzn is satisfiable'
            EDGE=$'\n    TODO: edge diff'
            echo $"FAILURE $1/$2 $ERR $EDGE"
        else
            echo $"SUCCESS $1/$2"
        fi
    fi
}

export PYTHONPATH="${PYTHONPATH}:../.."
if [ "$#" -eq 2 ]
then
    run $1 $2
    echo $'\nSee ca-output.txt for conflict analyzer output'
else
    for prog in global-alias global-alias-noaccess coerced-alias coerced-alias-noaccess heap heap-noaccess stack stack-noaccess indirect-xd indirect-coerce
    do
        run infeasible $prog
    done
    for prog in stack
    do
        run feasible $prog
    done
    rm ca-output.txt 2> /dev/null
fi